[project]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Physics Engine."
name = "thermo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test-geist = "magic run mojo test_geist.mojo"
test-thermo = "magic run mojo test_thermo.mojo"

[dependencies]
max = "==24.5.0"
sdl2 = ">=2.30.7,<3"
sdl2_gfx = ">=1.0.4,<2"
sdl2_image = ">=2.8.2,<3"
